import OBR from "https://cdn.jsdelivr.net/npm/@owlbear-rodeo/sdk@3.1.0/+esm";
const NS="com.lynx.fabula-unified",CHANNEL=`${NS}/events`,POPUP=`${NS}/companion-hud-menu-v1`;
let me={},players=[],all=true,targets=[],form={kind:"item",name:"",itemType:"",description:""};
const HUD_CHANNEL=`${NS}/companion-hud-control-v1`;
const esc=s=>String(s??"").replace(/[&<>'"]/g,x=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[x]));
const online=()=>{const rows=[{id:me.id,name:me.name,offline:false},...players],seen=new Set;return rows.filter(p=>p?.id&&!p.offline&&!seen.has(String(p.id))&&seen.add(String(p.id)))};
function render(msg=""){const list=online();targets=targets.filter(id=>list.some(p=>String(p.id)===id));document.querySelector('#app').innerHTML=`<header><small>FABULA ULTIMA · GM QUICK TOOL</small><h1>LOOT DISTRIBUTION</h1><p>Recipient must press RECEIVE before the card enters their Sheet.</p></header><section><label>CARD TYPE<select id="kind"><option value="item" ${form.kind==="item"?"selected":""}>ITEM</option><option value="sphere" ${form.kind==="sphere"?"selected":""}>SPHERE</option><option value="fp" ${form.kind==="fp"?"selected":""}>FABULA POINT · +1</option></select></label>${form.kind==="fp"?"":`<label>NAME<input id="name" maxlength="80" value="${esc(form.name)}" placeholder="e.g. Emberglass Key"></label><label>TYPE<input id="itemType" maxlength="80" value="${esc(form.itemType)}" placeholder="e.g. Key Item, Consumable, Fire"></label><label>DETAILS<textarea id="description" maxlength="1800" placeholder="Effect / description">${esc(form.description)}</textarea></label>`}<div class="target-head"><b>RECIPIENTS</b><button data-all class="small ${all?"active":""}">${all?"ALL CHARACTERS":"SELECT CHARACTERS"}</button></div><div class="targets">${list.map(p=>`<button data-player="${esc(p.id)}" class="${!all&&targets.includes(String(p.id))?"active":""}" ${all?"disabled":""}>${esc(p.name||"PLAYER")}</button>`).join("")||"<em>No online characters.</em>"}</div><div class="message">${esc(msg)}</div><footer><button data-close class="secondary">CLOSE</button><button data-send class="primary">SEND CARD</button></footer></section>`}
async function close(){try{await OBR.popover.close(POPUP)}catch{}}
function capture(){form.kind=document.querySelector('#kind')?.value||form.kind;for(const k of ['name','itemType','description']){const field=document.querySelector(`#${k}`);if(field)form[k]=field.value.trim()}}
async function send(){capture();const {kind}=form,to=all?["ALL_PLAYERS"]:targets;if(kind!=="fp"&&!form.name)return render("Enter a name.");if(!to.length)return render("Select at least one character.");const payload={id:`loot-${Date.now()}-${Math.random().toString(36).slice(2,7)}`,senderId:String(me.id||""),senderName:me.name||"GAME MASTER",kind,name:kind==="fp"?"FABULA POINT · +1":form.name.slice(0,80),itemType:kind==="fp"?"":form.itemType.slice(0,80),description:kind==="fp"?"":form.description.slice(0,1800),targets:to,time:Date.now()};try{await OBR.broadcast.sendMessage(CHANNEL,{type:"loot-card","loot-card":payload},{destination:"ALL"});if(to.includes("ALL_PLAYERS")||to.includes(String(me.id)))new BroadcastChannel(HUD_CHANNEL).postMessage({type:"loot-self-offer",payload});render("✓ Offer sent. Recipients can press RECEIVE.")}catch(e){render(`Could not send the card: ${e?.message||"Try again"}`)}}
document.addEventListener('change',e=>{if(e.target.id==='kind'){capture();render()}});document.addEventListener('click',async e=>{const b=e.target.closest('button');if(!b)return;if(b.hasAttribute('data-close'))return close();if(b.hasAttribute('data-all')){capture();all=!all;if(all)targets=[];return render()}if(b.dataset.player){capture();const id=String(b.dataset.player),i=targets.indexOf(id);if(i<0)targets.push(id);else targets.splice(i,1);return render()}if(b.hasAttribute('data-send'))await send()});
OBR.onReady(async()=>{if(await OBR.player.getRole()!=="GM"){document.body.textContent="GM only.";return}me={id:await OBR.player.getId(),name:await OBR.player.getName()};players=await OBR.party.getPlayers();OBR.party.onChange(p=>{players=p;render()});render()});
